name: Build and push Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * 2'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Build the Docker images
      - name: Build Docker images
        run: |
          docker build --target latest -t arnodirlam/alpine-watchexec-curl:latest .
          docker build --target certbot -t arnodirlam/alpine-watchexec-curl:certbot .
          docker build --target terraform -t arnodirlam/alpine-watchexec-curl:terraform .
          docker build --target terraform-openssl -t arnodirlam/alpine-watchexec-curl:terraform-openssl .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push the Docker images to Docker Hub
      - name: Push Docker images
        run: |
          docker push arnodirlam/alpine-watchexec-curl:latest
          docker push arnodirlam/alpine-watchexec-curl:certbot
          docker push arnodirlam/alpine-watchexec-curl:terraform
          docker push arnodirlam/alpine-watchexec-curl:terraform-openssl
